### ISSUE TITLE
Zigbee2Mqtt Join Network

### ISSUE THREAD

**Issue by pherting** [micromasterminds/esp32c6_zigbee_router_examples#3]
Hi, danke erstmal für deinen Code und deine Videos.
Allerdings stehe ich beim joinen meines Zigbee Netzwerks über Zigbee2Mqtt  leider auf dem Schlauch.
Ich klicke auf "Anlernen aktivieren" und es passiert nichts. Normalerweiße muss man nun das Zigbee gerät in Pairing Mode bringen, wie geht das beim ESP32 C6 dann? Automatisch? Sieht zumindest bei dir so aus..

Im Seriel Monitor erhalten ich nur die Meldung:

`22:13:13.717 -> [ 21847][I][signalHandler.ino:16] esp_zb_app_signal_handler(): Zigbee signal: BDB Steering
22:13:13.717 -> [ 21855][I][signalHandler.ino:58] esp_zb_app_signal_handler(): Network steering was not successful (status: ESP_FAIL)`

Vielleicht kannst du mir ja einen Tipp geben was ich falsch mache. Besten Dank!

**Comment by micromasterminds** [comment]
Hey, hast du "Erase All Flash before Sketch Upload" auf "Enabled" gestellt? Falls ja, versuche mal

`esp_zb_nvram_erase_at_start(true);`

vor 

`ESP_ERROR_CHECK(esp_zb_start(false));`
`esp_zb_main_loop_iteration();`

einzufügen. 
Beim nächsten Upload solltest du die Zeile dann aber wieder auskommentieren. Sonst "vergisst" der ESP den aktuellen Coordinator jedes mal. Der Pairing Mode sollte in allen anderen Fällen automatisch aktiviert werden.

**Comment by pherting** [comment]
Hey, danke für deine Rückmeldung!

Ich habe es soeben nochmal probiert, auch alles überprüft und gecheckt. Haken war gesetzt etc.
Leider immer noch die selbe Meldung!

Ich habe dann den ESP32C6 vom PC abgeschloßen, an eine Powerbank gesteckt und bin näher zum Raspi mit meinem ZigBee Stick gegangen und siehe da, verbindung kam direkt hoch ;)

Fürs erste Verbinden musste wohl der ESP einfach näher zur "Basis".. sobald er einmal verbunden ist, kann ich nun auch wieder zum PC zurück und in der Wohnung rumlaufen.

Besten Dank für deine Hilfe ;)
